apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-network-loss
  version: 0.1.1
  annotations:
    categories: Kubernetes
    vendor: CNCF
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: pod-network-loss
  description: >
    Pod-network-loss contains chaos to disrupt network connectivity to kubernetes pods. Experiments can inject percentage packet loss on the app replica pods. 
  keywords:
    - Kubernetes
    - Network
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-network-loss/experiment.yaml 
