apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: openebs-pool-container-failure
  version: 0.1.3
  annotations:
    categories: OpenEBS
    vendor: CNCF
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.openebs.io/
spec:
  displayName: openebs-pool-container-failure 
  categoryDescription: >
     Kill the pool container and check if gets scheduled again. 
  keywords:
    - Kubernetes
    - Storage Pool
    - OpenEBS
  platforms:
    - GKE
    - OpenShift
  maturity: alpha
  maintainers:
    - name: shubham chaudhary
      email: shubham.chaudhary@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  readme: "https://github.com/litmuschaos/litmus/blob/master/experiments/openebs/openebs-pool-container-failure/README.md"
  links:
    - name: OpenEBS Website
      url: https://openebs.io
    - name: Source Code
      url: https://github.com/openebs/openebs
  icon:
    - url: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/openebs/openebs-pool-container-failure/experiment.yaml
