apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kafka-broker-disk-failure
  version: 0.1.5
  annotations:
    categories: Kafka
    vendor: Mayadata
    support: https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN
spec:
  displayName: kafka-broker-disk-failure
  categoryDescription: |
     Detaching a persistent disk from a node/instance for kafka
  keywords:
    - Kubernetes
    - Disk
    - Kafka
  platforms:
    - GKE
    - konvoy
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus/tree/master/experiments/kafka/kafka-broker-disk-failure
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/kafka-broker-disk-failure/
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/kafka/kafka-broker-disk-failure/experiment.yaml
