apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Terminating azure VM instance
kind: ChaosExperiment
metadata:
  name: azure-instance-stop
  labels:
    name: azure-instance-stop
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "events"
          - "pods/log"
          - "pods/exec"
          - "secrets"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
    image: "litmuschaos/go-runner:ci"
    imagePullPolicy: Always
    args:
    - -c
    - ./experiments -name azure-instance-stop
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '30'

    - name: CHAOS_INTERVAL
      value: '30'

    # Period to wait before and after injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    # provide the target instance name(s) (comma separated if multiple)
    - name: AZURE_INSTANCE_NAME
      value: ''

    # provide the resource group of the instance
    - name: RESOURCE_GROUP
      value: ''
    
    # accepts enable/disable, default is disable
    - name: SCALE_SET
      value: ''

    # Provide the path of aks credentials mounted from secret  
    - name: AZURE_AUTH_LOCATION
      value: '/tmp/azure.auth'

    - name: SEQUENCE
      value: 'parallel'       

    # provide the LIB
    # only litmus supported
    - name: LIB
      value: 'litmus'  
          
    labels:
      name: azure-instance-stop
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
    secrets:
    - name: cloud-secret
      mountPath: /tmp/


---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Detaches disk from the VM and then re-attaches disk to the VM
kind: ChaosExperiment
metadata:
  name: azure-disk-loss
  labels:
    name: azure-disk-loss
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups: 
          - "" 
          - "batch" 
          - "apps" 
          - "litmuschaos.io"
        resources: 
          - "jobs" 
          - "pods" 
          - "pods/log" 
          - "events" 
          - "deployments" 
          - "replicasets" 
          - "pods/exec" 
          - "chaosengines" 
          - "chaosexperiments" 
          - "chaosresults"
          - "secrets"
        verbs: 
          - "create" 
          - "list" 
          - "get" 
          - "patch" 
          - "update" 
          - "delete" 
          - "deletecollection"
    image: "litmuschaos/go-runner:latest"
    imagePullPolicy: Always
    args:
    - -c
    - ./experiments -name azure-disk-loss
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '30' 

    - name: CHAOS_INTERVAL
      value: '30'

    - name: LIB
      value: 'litmus'

    # Period to wait before and after injection of chaos in sec
    - name: RAMP_TIME
      value: ''
    
    # provide the resource group of the instance
    - name: RESOURCE_GROUP
      value: ''
    
    # accepts enable/disable, default is disable
    - name: SCALE_SET
      value: ''
    
    # provide the virtual disk names (comma separated if multiple)
    - name: VIRTUAL_DISK_NAMES
      value: ''
    
    # provide the sequence type for the run. Options: serial/parallel
    - name: SEQUENCE
      value: 'parallel'
    
    # provide the path to aks credentials mounted from secret
    - name: AZURE_AUTH_LOCATION
      value: '/tmp/azure.auth'

    labels:
      name: azure-disk-loss
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
    
    secrets:
    - name: cloud-secret
      mountPath: /tmp/

---
