sudo: required
dist: xenial # ubuntu 16.04 distro
script:
  - make deps
  # runs  only when PR is merged
  - make versionmaker
after_success: 
   # runs only when PR is merged and push the version file to master version
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then make push; fi
