apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: gcp 
  version: 0.1.0
  annotations:
    categories: gcp
spec:
  displayName: gcp-vm-disk-loss-by-label 
  categoryDescription: >
    Stops GCP VM instances and GKE nodes filtered by a label for a specified duration of time and later restarts them 
  keywords: 
    - "VM"  
    - "GCP"
  platforms: 
    - "Minikube"
  maturity: alpha
  maintainers: 
    - name: Neelanjan Manna 
      email: neelanjan.manna@harness.io 
  minKubeVersion: 1.12.0 
  provider: 
    name: Harness
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: 2.9.0
  links: 
    - name: Documentation 
      url: https://litmuschaos.github.io/litmus/experiments/categories/gcp/gcp-vm-disk-loss-by-label/
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/gcp/gcp-vm-disk-loss-by-label/experiment.yaml
