apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: generic
  version: 0.1.8
  annotations:
    categories: Kubernetes
    chartDescription: Injects generic kubernetes chaos 
spec:
  displayName: Generic Chaos
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easy management and discovery. It will install all the experiments which can be used to inject chaos into containerized appications.

  experiments:
    - pod-delete
    - container-kill
    - pod-cpu-hog
    - pod-network-loss
    - pod-network-latency
    - pod-network-corruption
    - node-drain
    - node-cpu-hog
    - disk-loss
    - disk-fill

  keywords:
    - Kubernetes
    - Container
    - Node
    - Pod
    - Disk
    - Network
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/ 
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml
