packageName: kubernetes 
experiments:
  - name: pod-delete
    CSV: pod-delete.chartserviceversion.yaml
    desc: "pod delete"
  - name: container-kill
    CSV:  container-kill.chartserviceversion.yaml
    desc: "container kill"
  - name: pod-network-loss
    CSV: pod-network-loss.chartserviceversion.yaml
    desc: "pod network loss"
  - name: pod-network-latency
    CSV: pod-network-latency.chartserviceversion.yaml
    desc: "pod network latency"
