apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2019-09-26T10:28:08Z
  name: generic
  version: 0.1.16
  annotations:
    categories: Kubernetes
    chartDescription: Injects generic kubernetes chaos
spec:
  displayName: Generic Chaos
  categoryDescription: >
    Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.

  experiments:
    - kubelet-service-kill
  keywords:
    - Kubernetes
    - K8S
    - Container
    - Node
    - Pod
    - Disk
    - IO
    - Filesystem
    - Network
    - CPU
    - Memory
    - Stress
    - Service
    - DNS
    - Scale
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#generic
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml
