apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'   
  # It can be active/stop
  engineState: 'active'    
  chaosServiceAccount: pod-memory-hog-sa
  experiments:
    - name: pod-memory-hog
      spec:
        components:
          env:
            # Enter the amount of memory in megabytes to be consumed by the application pod
            - name: MEMORY_CONSUMPTION
              value: '500'

            - name: NUMBER_OF_WORKERS
              value: '1'              

            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds
