apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-05-15T10:28:08Z
  name: ebs-loss-by-tag
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: CNCF
    support: https://slack.kubernetes.io/
spec:
  displayName: ebs-loss-by-tag
  categoryDescription: |
    EBS Loss By Tag contains chaos to disrupt state of infra resources. The experiment can induce ebs volume loss against specified application for given volume tag. 
    - Causes ebs volume loss by tag from node or ec2 instance for certain chaos interval from total chaos duration.
    - Tests deployment sanity (replica availability & uninterrupted service) and recovery workflows of the application pod
  keywords:
    - EBS
    - Volume
    - AWS 
  platforms:
    - AWS
  maturity: alpha
  chaosType: infra
  maintainers:
    - name: Udit Gaurav
      email: uditgaurav@mayadata.io
  provider:
    name: Mayadata
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus-go/tree/master/experiments/kube-aws/ebs-loss-by-tag
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/aws/ebs-loss-by-tag/
    - name: Video
      url:
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/kube-aws/ebs-loss-by-tag/experiment.yaml
