---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-delete-sa
  namespace: default
  labels:
    name: vm-delete-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: vm-delete-sa
  namespace: default
  labels:
    name: vm-delete-sa
rules: [{'apiGroups': ['', 'batch', 'litmuschaos.io'], 'resources': ['jobs', 'pods', 'deployments','pods/log', 'events', 'chaosengines', 'chaosexperiments', 'chaosresults', 'secrets'], 'verbs': ['create', 'list', 'get', 'update', 'patch', 'delete','deletecollection']}]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: vm-delete-sa
  namespace: default
  labels:
    name: vm-delete-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-delete-sa
subjects:
- kind: ServiceAccount
  name: vm-delete-sa
  namespace: default

