apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-delete
  annotations:
    categories: "OpenEBS"
    vendor: "CNCF"
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/community-charts
    support: https://slack.openebs.io/
spec:
  displayName: Pod-Delete 
  description: >
     Pod delete contains chaos to disrupt state of openebs control-plane and  data-plane resources. Experiments can inject random pod delete against specified openebs replicas. 

  keywords:
    - Kubernetes
    - Pod
    - OpenEBS
  version: {{ VERSION }}
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: OpenEBS Website
      url: https://openebs.io
    - name: Source Code
      url: https://github.com/openebs/openebs
  icon:
    - url: ""
      mediatype: ""
