apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Pod DNS Error injects dns failure/error in target pod containers
kind: ChaosExperiment
metadata:
  name: pod-dns-error
  labels:
    name: pod-dns-error
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: 1.13.6
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "apps"
          - "apps.openshift.io"
          - "argoproj.io"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "replicasets"
          - "deploymentconfigs"
          - "rollouts"
          - "pods/exec"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
          - "deletecollection"
    image: "litmuschaos/go-runner:1.13.6"
    args:
      - -c
      - ./experiments -name pod-dns-error
    command:
      - /bin/bash
    env:
      - name: TARGET_CONTAINER
        value: ""

      # provide lib image
      - name: LIB_IMAGE
        value: "litmuschaos/go-runner:1.13.6"

      - name: TOTAL_CHAOS_DURATION
        value: "60" # in seconds

      # Time period to wait before and after injection of chaos in sec
      - name: RAMP_TIME
        value: ""

      ## percentage of total pods to target
      - name: PODS_AFFECTED_PERC
        value: ""

      - name: TARGET_PODS
        value: ""

      # provide the name of container runtime, it supports docker, containerd, crio
      - name: CONTAINER_RUNTIME
        value: "docker"

      # provide the socket file path
      - name: SOCKET_PATH
        value: "/var/run/docker.sock"

      ## it defines the sequence of chaos execution for multiple target pods
      ## supported values: serial, parallel
      - name: SEQUENCE
        value: "parallel"

      # list of the target hostnames or kewywords eg. '["litmuschaos","chaosnative.io"]' . If empty all hostnames are targets
      - name: TARGET_HOSTNAMES
        value: ""

      # can be either exact or substring, determines whether the dns query has to match exactly with one of the targets or can have any of the targets as substring
      - name: MATCH_SCHEME
        value: "exact"

    labels:
      experiment: pod-dns-error
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: 1.13.6
