apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: gcp-vm-instance-stop 
  version: 0.1.0
  annotations:
    categories: gcp
spec:
  displayName: gcp-vm-instance-stop 
  categoryDescription: >
    Stops GCP VM instances and GKE nodes for a specified duration of time and later restarts them 
  keywords: 
    - "VM" 
    - "GCP" 
  platforms: 
    - "GCP"
  maturity: alpha
  maintainers: 
    - name: Neelanjan Manna 
      email: neelanjan@chaosnative.com 
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links: 
    - name: Documentation 
      url: https://litmuschaos.github.io/litmus/experiments/categories/gcp/gcp-vm-instance-stop/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/gcp/gcp-vm-instance-stop/experiment.yaml
