apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: container-kill
  version: 0.1.6
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    support: https://slack.openebs.io/
spec:
  displayName: container-kill
  categoryDescription: |
   Container kill contains chaos to disrupt state of kubernetes resources. Experiments can inject random container delete failures against specified application. 
    - Executes SIGKILL on containers of random replicas of an application deployment.
    - Tests deployment sanity (replica availability & uninterrupted service) and recovery workflows of the application pod.
  keywords:
    - Kubernetes
    - Container 
  platforms:
    - GKE
    - OpenShift
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Docs
      url: https://docs.litmuschaos.io/docs/container-kill/
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/container-kill/experiment.yaml
