apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: container-kill
  version: 0.1.1
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.openebs.io/
spec:
  displayName: container-kill
  categoryDescription: >
   Container kill contains chaos to disrupt state of kubernetes resources. Experiments can inject random container delete failures against specified application. 
  keywords:
    - Kubernetes
    - Container 
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/container-kill/experiment.yaml
