apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2019-10-15T10:28:08Z
  name: pod-delete
  version: 0.1.13
  annotations:
    categories: Kubernetes
    vendor: CNCF
    support: https://slack.kubernetes.io/
spec:
  displayName: pod-delete
  categoryDescription: |
    Pod delete contains chaos to disrupt state of kubernetes resources. Experiments can inject random pod delete failures against specified application.
    - Causes (forced/graceful) pod failure of random replicas of an application deployment.
    - Tests deployment sanity (replica availability & uninterrupted service) and recovery workflows of the application pod.
 
  keywords:
    - Kubernetes
    - State 
  platforms:
    - GKE
    - Konvoy
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus-go/tree/master/experiments/generic/pod-delete
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/pod-delete/
    - name: Video
      url: https://www.youtube.com/watch?v=X3JvY_58V9A
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/pod-delete/experiment.yaml
