apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: cpu-hog
  version: 0.0.1
  annotations:
    categories: Kubernetes
    vendor: CNCF
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: cpu-hog
  categoryDescription: |
    CPU hog contains chaos to disrupt state of kubernetes resources. Experiments can inject a cpu skipe on a node where the application pod is scheduled.
    - Causes (forced/graceful) cpu hog on a perticular node where the application deployment is available.
    - After test the recovery should be manual of the application pod and node in case they are not in appropriate state.
 
  keywords:
    - Kubernetes
    - CPU
    - State 
  platforms:
    - GKE
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/cpu-hog/experiment.yaml
