apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: kubernetes-network 
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/community-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: network
  description: >
    Kubernetes subchart networkChaos which contains chaos to disrupt network connectivity of kubernetes pods. Experiments can inject random network jitters, delays and packet loss on the app replica pods. Install will add the following experiments
    - pod-nw-delay-exp.yaml
  keywords:
    - Kubernetes
    - Network
  version: {{ VERSION }}
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - base64data: ""
      mediatype: ""
  experiments:
    - pod-nw-delay-exp.yaml

