apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Stops one or more VMs for a certain chaos duration.
kind: ChaosExperiment
metadata:
  name: vm-poweroff
  labels:
    name: vm-poweroff
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "events"
          - "pods/log"
          - "pods/exec"
          - "secrets"            
          - "pods"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "update"
          - "patch"
          - "delete"
    image: "litmuschaos/go-runner:latest"
    args:
    - -c
    - ./experiments -name vm-poweroff
    command:
    - /bin/bash
    env:

    - name: VCENTERSERVER
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERSERVER

    - name: VCENTERUSER
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERUSER

    - name: VCENTERPASS
      valueFrom:
        secretKeyRef:
          name: vcenter-secret
          key: VCENTERPASS

    # provide the VM MOIDs as comma separated values
    - name: APP_VM_MOIDS
      value: ''
          
    # set chaos duration (in sec) as desired
    - name: TOTAL_CHAOS_DURATION
      value: '30'

    # set chaos interval (in sec) as desired
    - name: CHAOS_INTERVAL
      value: '30'

    - name: LIB
      value: 'litmus'

    - name: RAMP_TIME
      value: ''

    # parallel or sequence; the mode of chaos sequence, defaults to parallel
    - name: SEQUENCE
      value: 'parallel'

    labels:
      experiment: vm-poweroff
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
