apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: disk-fill
  version: 0.0.2
  annotations:
    categories: Kubernetes
    vendor: CNCF
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: disk-fill
  categoryDescription: |
    Disk fill contains chaos to disrupt state of kubernetes resources. 
    - Causes (forced/graceful) Disk Stress by filling up the Ephemeral Storage of the Pod using one of it containers.
    - Causes Pod to get Evicted if the Pod exceeds it Ephemeral Storage Limit.
    - Tests the Ephemeral Storage Limits, to ensure those parameters are sufficient.
 
  keywords:
    - Kubernetes
    - Disk
    - State 
  platforms:
    - GKE
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Docs 
      url: https://docs.litmuschaos.io/docs/disk-fill/
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/disk-fill/experiment.yaml
