apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: disk-fill-sa
  experiments:
    - name: disk-fill
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # specify the fill percentage according to the disk pressure required
            - name: FILL_PERCENTAGE
              value: '80'

            - name: PODS_AFFECTED_PERC
              value: ''

            # provide the name of container runtime, it supports docker, containerd, crio
            - name: CONTAINER_RUNTIME
              value: 'containerd'

            # provide the socket file path
            - name: SOCKET_PATH
              value: '/run/containerd/containerd.sock'
