apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2019-08-12T10:28:08Z
  name: openebs-target-container-failure
  version: 0.1.8
  annotations:
    categories: OpenEBS
    vendor: CNCF
    support: https://slack.openebs.io/
spec:
  displayName: openebs-target-container-failure 
  categoryDescription: >
     Kill the cstor target/Jiva controller container and check if gets created again
  keywords:
    - Kubernetes
    - Storage Controller
    - OpenEBS
  platforms:
    - GKE
    - OpenShift
  maturity: alpha
  maintainers:
    - name: shubham chaudhary
      email: shubham.chaudhary@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus/tree/master/experiments/openebs/openebs-target-container-failure
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/openebs-target-container-failure/
    - name: Video
      url:
  icon:
    - url: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/openebs/openebs-target-container-failure/experiment.yaml
