---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-taint
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: LitmusChaos
spec:
  displayName: Node Taint
  categoryDescription: >
    Taint the node where application pod is scheduled.
  keywords:
    - Kubernetes
  platforms:
    - GKE
    - AWS(KOPS)
    - Packet(Kubeadm)
    - Konvoy
    - EKS
    - AKS
  maintainers:
    - name: Shubham Chaudhary
      email: shubham.chaudhary@harness.io
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
  icon:
    - url: ""
      mediatype: ""
