---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-poweroff
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: LitmusChaos
spec:
  displayName: Node Poweroff
  categoryDescription: |
    Node poweroff contains chaos experiment to poweroff a node via SSH.
  keywords:
    - Kubernetes
  platforms:
    - KVM/LibVirt based K8s
    - EKS
  maintainers:
    - name: jordigilh
      email: jordi.gil@gmail.com
  chaosType: infra
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
  icon:
    - url: ""
      mediatype: ""
