apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: openebs-target-pod-failure
  version: 0.1.5
  annotations:
    categories: OpenEBS
    vendor: CNCF
    support: https://slack.openebs.io/
spec:
  displayName: openebs-target-pod-failure 
  categoryDescription: >
     Kill the cstor target/Jiva controller pod and check if gets created again
  keywords:
    - Kubernetes
    - Storage Controller
    - OpenEBS
  platforms:
    - GKE
    - OpenShift
  maturity: alpha
  chaosType: app-level
  maintainers:
    - name: shubham chaudhary
      email: shubham.chaudhary@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: OpenEBS Website
      url: https://openebs.io
    - name: Source Code
      url: https://github.com/openebs/openebs
    - name: Docs
      url: https://docs.litmuschaos.io/docs/openebs-target-pod-failure/      
  icon:
    - url: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/openebs/openebs-target-pod-failure/experiment.yaml

