apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: openebs
  version: 0.1.10
  annotations:
    categories: OpenEBS
    vendor: MayaData
    repository: https://github.com/litmuschaos/chaos-charts
    support: https://slack.openebs.io/
    description: Injects generic openebs chaos 
spec:
  displayName: OpenEBS
  description: >
    OpenEBS is the most active Container Attached Storage project. OpenEBS enables your DevOps teams to have their own storage policies for every workload and it is truly Kubernetes native and 100% in userspace. 

  experiments:
    - openebs-pool-failures
    - openebs-target-failures
    - openebs-target-network-delayss
    - openebs-target-network-loss
  keywords:
    - OpenEBS
    - CAS
    - Storage
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: OpenEBS Website
      url: https://openebs.io
    - name: Source Code
      url: https://github.com/openebs/openebs
  icon:
    - url: 
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/openebs/experiments.yaml
