packageName: openebs
experiments:
  - name: openebs-pool-failure
    CSV: openebs-pool-failure.chartserviceversion.yaml 
    desc: "openebs-pool-failure"
  - name: openebs-target-failure
    CSV: openebs-target-failure.chartserviceversion.yaml 
    desc: "openebs-target-failure"
  - name: openebs-target-network-delay
    CSV: openebs-target-network-delay.chartserviceversion.yaml 
    desc: "openebs-target-network-delay"
  - name: openebs-target-network-loss
    CSV: openebs-target-network-loss.chartserviceversion.yaml 
    desc: "openebs-target-network-loss"
    
