apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: pod-network-delay-v0.1.0 
  annotations:
    categories: "Kubernetes"
    vendor: "CNCF"
    createdAt: 2019-08-12T10:28:08Z
    repository: https://github.com/litmuschaos/community-charts
    support: https://slack.kubernetes.io/
spec:
  displayName: pod-network-delay
  description: >
    Pod-network-delay contains chaos to disrupt network connectivity of kubernetes pods. Experiments can inject random network jitters, delays and packet loss on the app replica pods. 
  keywords:
    - Kubernetes
    - Network
  version: 0.1.0
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
  icon:
    - base64data: ""
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/community-charts/master/charts/kubernetes/network/experiments/k8s_nw_all_exp_crd.yaml 
