apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2019-01-28T10:28:08Z
  name: node-cpu-hog
  version: 0.0.15
  annotations:
    categories: Kubernetes
    vendor: CNCF
    support: https://slack.kubernetes.io/
spec:
  displayName: node-cpu-hog
  categoryDescription: |
    Node CPU hog contains chaos to disrupt the state of Kubernetes resources. Experiments can inject a CPU spike on a node where the application pod is scheduled.
    - CPU hog on a particular node where the application deployment is available.
    - After test, the recovery should be manual for the application pod and node in case they are not in an appropriate state.
  keywords:
    - Kubernetes
    - CPU
    - State
    - Node
  platforms:
    - GKE
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maturity: alpha
  chaosType: infra
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus-go/tree/master/experiments/generic/node-cpu-hog
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/node-cpu-hog/
    - name: Video
      url: https://www.youtube.com/watch?v=jpJttftsZqA
  icon: 
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/node-cpu-hog/experiment.yaml
