apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2019-08-12T10:28:08Z
  name: node-cpu-hog
  version: 0.0.8
  annotations:
    categories: Kubernetes
    vendor: CNCF
    support: https://slack.kubernetes.io/
spec:
  displayName: node-cpu-hog
  categoryDescription: |
    Node CPU hog contains chaos to disrupt state of kubernetes resources. Experiments can inject a cpu skipe on a node where the application pod is scheduled.
    - Causes (forced/graceful) cpu hog on a perticular node where the application deployment is available.
    - After test the recovery should be manual of the application pod and node in case they are not in appropriate state.
 
  keywords:
    - Kubernetes
    - CPU
    - State 
  platforms:
    - GKE
  maturity: alpha
  chaosType: infra
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Source Code
      url: https://github.com/litmuschaos/litmus/tree/master/experiments/generic/node_cpu_hog
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/node-cpu-hog/
    - name: Video
      url:
  icon: 
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/node-cpu-hog/experiment.yaml